/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println("test1");
        System.out.println("test2");
    }
}
